export const RECEIVE_BOARDS = "RECEIVE_BOARDS"
export const ADD_BOARD = 'ADD_BOARD'
export const REMOVE_BOARD = 'REMOVE_BOARD'
export const RECEIVE_BOARD = 'RECEIVE_BOARD'
export const RECEIVE_CARDS = "RECEIVE_CARDS"
export const RENAME_BOARD = 'RENAME_BOARD'

export const ADD_LIST = "ADD_LIST"
export const REMOVE_LIST = "REMOVE_LIST"
export const RENAME_LIST = "RENAME_LIST"

export const ADD_CARD = "ADD_CARD"
export const REMOVE_CARD = "REMOVE_CARD"
export const RENAME_CARD = "RENAME_CARD"
export const MIGRATE_CARD = "MIGRATE_CARD"
export const EDIT_CARD_DESCRIPTION = "EDIT_CARD_DESCRIPTION"
