"""empty message

Revision ID: c25f4328a325
Revises: 61448c1c0e47
Create Date: 2019-02-06 15:00:57.749913

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c25f4328a325'
down_revision = '61448c1c0e47'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('card', sa.Column('description', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('card', 'description')
    # ### end Alembic commands ###
